apiVersion: front.in-cloud.io/v1alpha1
kind: Factory
metadata:
  name: clusterrole-details
spec:
  key: clusterrole-details
  sidebarTags:
    - clusterrole-details
  withScrollableMainContentCard: true
  urlsToFetch:
    - cluster: "{2}"
      group: "rbac.authorization.k8s.io"
      version: "v1"
      plural: "clusterroles"
      fieldSelector: "metadata.name={5}"

  # Header row with badge and clusterrole name
  data:
    - type: antdFlex
      data:
        id: header-row
        gap: 6
        align: center
        style:
          marginBottom: 24px
      children:
        # resource badge
        - type: ResourceBadge
          data:
            id: factory-resource-badge
            value: ClusterRole
            style:
              fontSize: 20px

        # resource name
        - type: parsedText
          data:
            id: service-name
            text: "{reqsJsonPath[0]['.items.0.metadata.name']['-']}"
            style:
              fontSize: 20px
              lineHeight: 24px
              fontFamily: RedHatDisplay, Overpass, overpass, helvetica, arial, sans-serif

    # Tabs with Details, YAML, and Pods
    - type: antdTabs
      data:
        id: service-tabs
        defaultActiveKey: "details"
        items:
          # Details tab
          - key: "details"
            label: "Details"
            children:
              - type: ContentCard
                data:
                  id: details-card
                  style:
                    marginBottom: 24px
                children:
                  - type: antdRow
                    data:
                      id: details-grid
                      gutter: [48, 12]
                    children:
                      # Left column: metadata and config
                      - type: antdCol
                        data:
                          id: col-left
                          span: 12
                        children:
                          - type: antdText
                            data:
                              id: details-title
                              text: "ClusterRole details"
                              strong: true
                              style:
                                fontSize: 20
                                marginBottom: 12px
                          - type: Spacer
                            data:
                              id: details-spacer
                              "$space": 16
                          - type: antdFlex
                            data:
                              id: col-left-stack
                              vertical: true
                              gap: 24
                            children:
                              # Name block
                              - type: antdFlex
                                data:
                                  id: meta-name-block
                                  vertical: true
                                  gap: 4
                                children:
                                  - type: antdText
                                    data:
                                      id: meta-name-label
                                      strong: true
                                      text: "Name"
                                  - type: parsedText
                                    data:
                                      id: meta-name-value
                                      text: "{reqsJsonPath[0]['.items.0.metadata.name']['-']}"

                              # Labels
                              - type: antdFlex
                                data:
                                  id: meta-labels-block
                                  vertical: true
                                  gap: 8
                                children:
                                 {{ include "incloud-web-resources.factory.labels" (dict
                                      "endpoint" "/api/clusters/{2}/k8s/apis/rbac.authorization.k8s.io/v1/clusterroles/{5}"
                                      "linkPrefix" "/openapi-ui/{2}/search?kinds=rbac.authorization.k8s.io~v1~clusterroles&labels="
                                      "jsonPath" ".items.0.metadata.labels"
                                    ) | nindent 34
                                  }}

                              # Annotations counter block
                              - type: antdFlex
                                data:
                                  id: ds-annotations
                                  vertical: true
                                  gap: 4
                                children:
                                  {{ include "incloud-web-resources.factory.annotations.block" (dict
                                      "endpoint" "/api/clusters/{2}/k8s/apis/rbac.authorization.k8s.io/v1/clusterroles/{5}"
                                      "jsonPath" ".items.0.metadata.annotations"
                                      "pathToValue" "/metadata/annotations"
                                    ) | nindent 34
                                  }}

                              # Created timestamp
                              - type: antdFlex
                                data:
                                  id: meta-created-block
                                  vertical: true
                                  gap: 4
                                children:
                                  {{ include "incloud-web-resources.factory.time.create" (dict
                                    "req" ".items.0.metadata.creationTimestamp"
                                    "text" "Created"
                                    ) | nindent 34
                                  }}

                  - type: antdCol
                    data:
                      id: rule-col
                      style:
                        marginTop: 10
                        padding: 10
                    children:
                      - type: antdText
                        data:
                          id: rule-title
                          text: "Rules"
                          strong: true
                          style:
                            fontSize: 22
                      # Conditions table
                      - type: EnrichedTable
                        data:
                          id: conditions-table
                          clusterNamePartOfUrl: "{2}"
                          customizationId: factory-k8s-rbac-rules
                          baseprefix: "/{{ .Values.basePrefix }}"
                          pathToItems: ".items.0.rules"
                          k8sResourceToFetch: 
                            version: "v1"
                            group: "rbac.authorization.k8s.io"
                            plural: "clusterroles"
                          fieldSelector:
                            metadata.name: "{5}"

          # YAML tab
          - key: "yaml"
            label: "YAML"
            children:
              - type: YamlEditorSingleton
                data:
                  id: yaml-editor
                  cluster: "{2}"
                  isNameSpaced: false
                  type: "apis"
                  prefillValuesRequestIndex: 0
                  substractHeight: 400
                  pathToData: .items.0
                  typeName: clusterroles
                  forcedKind: ClusterRole
                  apiGroup:  "rbac.authorization.k8s.io"
                  apiVersion: v1
