---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-cluster-search-page
spec:
  id: stock-cluster-search-page
  breadcrumbItems:
    - key: search
      label: "search"
    - key: resources
      label: "resources"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-namespace-search-page
spec:
  id: stock-namespace-search-page
  breadcrumbItems:
    - key: search
      label: "search"
    - key: resources
      label: "resources"
