---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-status-init-containers-list
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .imageID
      name: Image
      type: string
    - jsonPath: .started
      name: Started
      type: bool
    - jsonPath: .ready
      name: Ready
      type: bool
    - jsonPath: .restartCount
      name: RestartCount
      type: string
    - jsonPath: .state.waiting.reason
      name: WaitingdReason
      type: string
    - jsonPath: .state.terminated.reason
      name: TerminatedReason
      type: string

  additionalPrinterColumnsUndefinedValues:
    - key: TerminatedReason
      value: "-"
    - key: WaitingdReason
      value: "-"

  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.container-image" . | nindent 4 }}
  id: "container-status-init-containers-list"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-status-containers-list
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .imageID
      name: Image
      type: string
    - name: Memory
      # Фильтрация недоступна до создания бекенда
      # jsonPath: .metadata.name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: ConverterBytes
            id: name-custom
            data:
              notANumberText: "-"
              bytesValue: |
                {reqsJsonPath[0]['.additionalReqsData.0.items[*].containers[?(@.name=="{reqsJsonPath[0][".name"]}")].usage.memory']['-']}

    - name: CPU
      # Фильтрация недоступна до создания бекенда
      # jsonPath: .metadata.name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: ConverterCores
            id: name-custom
            data:
              unit: true
              format: true
              precision: 4
              notANumberText: "-"
              coresValue: |
                {reqsJsonPath[0]['.additionalReqsData.0.items[*].containers[?(@.name=="{reqsJsonPath[0][".name"]}")].usage.cpu']['-']}

    - jsonPath: .started
      name: Started
      type: bool
    - jsonPath: .ready
      name: Ready
      type: bool
    - jsonPath: .restartCount
      name: RestartCount
      type: string
    - jsonPath: .state.waiting.reason
      name: WaitingdReason
      type: string
    - jsonPath: .state.terminated.reason
      name: TerminatedReason
      type: string

  additionalPrinterColumnsUndefinedValues:
    - key: TerminatedReason
      value: "-"
    - key: WaitingdReason
      value: "-"
  additionalPrinterColumnsCustomSortersAndFilters:
    - key: Memory
      type: memory
    - key: CPU
      type: cpu
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.container-image" . | nindent 4 }}
  id: "container-status-containers-list"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-spec-init-containers-list
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .image
      name: Image
      type: string
    - jsonPath: .resources.requests
      name: Resources requests
      type: array
    - jsonPath: .resources.limits
      name: Resources limits
      type: array
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.container-image" . | nindent 4 }}
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Image
      value: "-"
    - key: Resources limits
      value: "-"
    - key: Resources requests
      value: "-"
  id: container-spec-init-containers-list

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-spec-containers-list
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .image
      name: Image
      type: string
    - jsonPath: .resources.requests
      name: Resources requests
      type: array
    - jsonPath: .resources.limits
      name: Resources limits
      type: array
    - jsonPath: .ports[*].containerPort
      name: Ports
      type: array
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.container-image" . | nindent 4 }}
  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: Image
      value: "-"
    - key: Resources limits
      value: "-"
    - key: Resources requests
      value: "-"
    - key: Ports
      value: "-"
  id: container-spec-containers-list

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: container-metrics
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .usage.cpu
      name: CPU Usage
      type: string
    - jsonPath: .usage.memory
      name: Memory Usage
      type: string

  additionalPrinterColumnsUndefinedValues:
    - key: Name
      value: "-"
    - key: CPU Usage
      value: "-"
    - key: Memory Usage
      value: "-"

  id: container-metrics
