{{ $projRes := .Values.projectResource }}

{{ if and ($projRes.deployDefaultForms) (not .Values.namespaceNavigation) }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-project
spec:
  additionalPrinterColumns:
    - jsonPath: .metadata.name
      name: Name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.icon" (dict
            "text" "P"
            "title" "project"
            "backgroundColor" "#004080"
          )| nindent 8
        }}
        {{ include "incloud-web-resources.factory.linkblock" (dict
            "reqIndex" 0
            "type" "name"
            "jsonPath" ".metadata.name"
            "factory" "project-details"
            "namespace" "{reqsJsonPath[0]['.metadata.name']['-']}"
          ) | nindent 12 
        }}
    - jsonPath: .metadata.creationTimestamp
      name: Created
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.factory.timeblock" (dict
          "req" ".metadata.creationTimestamp"
          ) | nindent 8
        }}
  additionalPrinterColumnsTrimLengths:
    - key: Name
      value: 64
  additionalPrinterColumnsUndefinedValues: []
  id: "stock-cluster-/{{ $projRes.apiGroup }}/{{ $projRes.apiVersion }}/{{ $projRes.resourceName }}"
{{ end }}
