---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-rbac.authorization.k8s.io.v1.clusterrolebindings
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "CRB"
      "title" "ClusterRoleBinding"
      "backgroundColor" "#008bad"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "factory" "clusterrolebinding-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - jsonPath: .roleRef.name
      name: Role ref
      type: string
    - jsonPath: .subjects[?(@.kind=="ServiceAccount")].name
      name: Service accounts
      type: array
    - jsonPath: .subjects[?(@.kind=="User")].name
      name: Users
      type: array
    - jsonPath: .subjects[?(@.kind=="Group")].name
      name: Groups
      type: array
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.rbac-role-ref" . | nindent 4 }}
  additionalPrinterColumnsUndefinedValues:
    - key: Role ref
      value: "-"
    - key: Users
      value: "-"
    - key: Groups
      value: "-"
    - key: Service accounts
      value: "-"
    - key: Namespace
      value: "All namespaces"
  id: stock-cluster-/rbac.authorization.k8s.io/v1/clusterrolebindings
