---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-rbac.authorization.k8s.io.v1.clusterroles
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "CR"
      "title" "clusterrole"
      "backgroundColor" "#c46100"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "factory" "clusterrole-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
  id: stock-cluster-/rbac.authorization.k8s.io/v1/clusterroles
