---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-v1.nodes
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "Node"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "factory" "node-details/v1/nodes"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}

    - name: Memory
      # Фильтрация недоступна до создания бекенда
      # jsonPath: .metadata.name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: ConverterBytes
            id: name-custom
            data:
              notANumberText: "-"
              bytesValue: |
                {reqsJsonPath[0]['.additionalReqsData.0.items[?(@.metadata.name=="{reqsJsonPath[0][".metadata.name"]}")].usage.memory']['-']}

    - name: CPU
      # Фильтрация недоступна до создания бекенда
      # jsonPath: .metadata.name
      type: factory
      customProps:
        disableEventBubbling: true
        items:
          - type: ConverterCores
            id: name-custom
            data:
              unit: true
              format: true
              precision: 4
              notANumberText: "-"
              coresValue: |
                {reqsJsonPath[0]['.additionalReqsData.0.items[?(@.metadata.name=="{reqsJsonPath[0][".metadata.name"]}")].usage.cpu']['-']}


    - name: Status
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.cco.statuses.node" . | nindent 8 }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
  id: stock-cluster-/v1/nodes


---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-namespace-v1.nodes
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "Node"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "factory" "node-details/v1/nodes"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - name: Status
      type: factory
      customProps:
        disableEventBubbling: true
        items:
        {{ include "incloud-web-resources.cco.statuses.node" . | nindent 8 }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
  id: stock-namespace-/v1/nodes
