---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-cluster-apps.v1.replicationcontroller"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "ReplicationController"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "replicationcontroller-details/v1/replicationcontrollers"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Namespace"
      "title" "Namespace"
      "reqIndex" 0
      "type" "namespace"
      "jsonPath" ".metadata.namespace"
      "factory" "namespace-details/v1/namespaces"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.labels-new" (dict
        "endpoint" "/api/clusters/{2}/k8s/apis/apps/v1/daemonsets/{6}"
        "linkPrefix" "/openapi-ui/{2}/search?kinds=apps~v1~daemonsets&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.pod-selector" (dict
        "type" "pod"
        "jsonPath" ".spec.template.metadata.labels"
        "linkPrefix" "/openapi-ui/{2}/search?kinds=~v1~pods&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.labels" . | nindent 4 }}
  id: "stock-cluster-/v1/replicationcontrollers"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-namespace-apps.v1.replicationcontroller"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "ReplicationController"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "replicationcontroller-details/v1/replicationcontrollers"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.labels-new" (dict
        "endpoint" "/api/clusters/{2}/k8s/apis/apps/v1/daemonsets/{6}"
        "linkPrefix" "/openapi-ui/{2}/{3}/search?kinds=apps~v1~daemonsets&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.pod-selector" (dict
        "type" "pod"
        "jsonPath" ".spec.template.metadata.labels"
        "linkPrefix" "/openapi-ui/{2}/{3}/search?kinds=~v1~pods&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.labels" . | nindent 4 }}
  id: "stock-namespace-/v1/replicationcontrollers"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-project-apps.v1.replicationcontroller"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "ReplicationController"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "replicationcontroller-details/v1/replicationcontrollers"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.labels-new" (dict
        "endpoint" "/api/clusters/{2}/k8s/apis/apps/v1/daemonsets/{6}"
        "linkPrefix" "/openapi-ui/{2}/{3}/search?kinds=apps~v1~daemonsets&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.pod-selector" (dict
        "type" "pod"
        "jsonPath" ".spec.template.metadata.labels"
        "linkPrefix" "/openapi-ui/{2}/{3}/search?kinds=~v1~pods&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.labels" . | nindent 4 }}
  id: "stock-project-/v1/replicationcontrollers"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-instance-apps.v1.replicationcontroller"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "ReplicationController"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "project" "{4}"
      "factory" "instance-replicationcontroller-details/v1/replicationcontrollers"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.labels-new" (dict
        "endpoint" "/api/clusters/{2}/k8s/apis/apps/v1/daemonsets/{6}"
        "linkPrefix" "/openapi-ui/{2}/{3}/search?kinds=apps~v1~daemonsets&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.pod-selector" (dict
        "type" "pod"
        "jsonPath" ".spec.template.metadata.labels"
        "linkPrefix" "/openapi-ui/{2}/{3}/search?kinds=~v1~pods&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.labels" . | nindent 4 }}
  id: "stock-instance-/v1/replicationcontrollers"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "factory-replicationcontroller-details-volume-list"
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
  id: "factory-replicationcontroller-details-volume-list"
