---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-cluster-apps.v1.replicationcontroller"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "RC"
      "title" "ReplicationController"
      "backgroundColor" "#004080"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "replicationcontroller-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Namespace"
      "text" "N"
      "title" "Namespace"
      "backgroundColor" "#a25792ff"
      "reqIndex" 0
      "type" "namespace"
      "jsonPath" ".metadata.namespace"
      "factory" "namespace-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.labels" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns.pod-selector" (dict
        "type" "pod"
        "jsonPath" ".spec.template.metadata.labels"
        "linkPrefix" "/openapi-ui/{2}/search?kinds=~v1~pods&labels="
      ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.labels" . | nindent 4 }}
  id: "stock-cluster-/v1/replicationcontrollers"

{{ if .Values.namespaceNavigation }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-namespace-apps.v1.replicationcontroller"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "RC"
      "title" "ReplicationController"
      "backgroundColor" "#004080"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "replicationcontroller-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - jsonPath: .metadata.labels
      name: Labels
      type: string
    - jsonPath: .metadata.ownerReferences[*].name
      name: Owner
      type: string
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.labels" . | nindent 4 }}
  id: "stock-namespace-/v1/replicationcontrollers"
{{ else }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-project-apps.v1.replicationcontroller"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "RC"
      "title" "ReplicationController"
      "backgroundColor" "#004080"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "replicationcontroller-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - jsonPath: .metadata.labels
      name: Labels
      type: string
    - jsonPath: .metadata.ownerReferences[*].name
      name: Owner
      type: string
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.labels" . | nindent 4 }}
  id: "stock-project-/v1/replicationcontrollers"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-instance-apps.v1.replicationcontroller"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "RC"
      "title" "ReplicationController"
      "backgroundColor" "#004080"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "project" "{4}"
      "factory" "instance-replicationcontroller-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - jsonPath: .metadata.labels
      name: Labels
      type: string
    - jsonPath: .metadata.ownerReferences[*].name
      name: Owner
      type: string
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.labels" . | nindent 4 }}
  id: "stock-instance-/v1/replicationcontrollers"
{{ end }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "factory-replicationcontroller-details-volume-list"
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
  id: "factory-replicationcontroller-details-volume-list"
