---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-cluster-v1.serviceaccounts
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "SA"
      "title" "ServiceAccount"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "serviceaccount-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Namespace"
      "text" "N"
      "title" "Namespace"
      "backgroundColor" "#a25792ff"
      "reqIndex" 0
      "type" "namespace"
      "jsonPath" ".metadata.namespace"
      "factory" "namespace-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - jsonPath: .secrets[*].name
      name: Secrets
      type: array
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsUndefinedValues:
    - key: Namespace
      value: "-"
    - key: Secrets
      value: "-"
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.sa-secrets" . | nindent 4 }}
  id: stock-cluster-/v1/serviceaccounts

{{ if .Values.namespaceNavigation }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-namespace-v1.serviceaccounts
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "SA"
      "title" "ServiceAccount"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "serviceaccount-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - jsonPath: .secrets
      name: Secrets
      type: array
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsUndefinedValues:
    - key: Secrets
      value: "-"
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.sa-secrets" . | nindent 4 }}
  id: stock-namespace-/v1/serviceaccounts
{{ else }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-project-v1.serviceaccounts
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "SA"
      "title" "ServiceAccount"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "serviceaccount-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - jsonPath: .secrets
      name: Secrets
      type: array
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsUndefinedValues:
    - key: Secrets
      value: "-"
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.sa-secrets" . | nindent 4 }}
  id: stock-project-/v1/serviceaccounts

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: stock-instance-v1.serviceaccounts
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "SA"
      "title" "ServiceAccount"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "project" "{4}"
      "factory" "instance-serviceaccount-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    - jsonPath: .secrets
      name: Secrets
      type: array
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsUndefinedValues:
    - key: Secrets
      value: "-"
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
    {{ include "incloud-web-resources.cco.columns-trim-lengths.sa-secrets" . | nindent 4 }}
  id: stock-instance-/v1/serviceaccounts
{{ end }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: factory-serviceaccount-secrets
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "SA"
      "title" "ServiceAccount"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "secret-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
  id: factory-serviceaccount-secrets
