{{- $factoryID := "instance-certificate-details" -}}
{{ if .Values.namespaceNavigation }}
  {{- $factoryID = "certificate-details" -}}
{{ end }}

---
apiVersion: front.in-cloud.io/v1alpha1
kind: Sidebar
metadata:
  name: "stock-instance-factory-{{ $factoryID }}"
spec:
  id: "stock-instance-factory-{{ $factoryID }}"
  # keysAndTags:
  #   certificates:
  #     - '{reqsJsonPath[0][".apiVersion"]["-"]}/{reqsJsonPath[0][".kind"]["-"]}'
  menuItems:
  {{ if .Values.namespaceNavigation }}
    {{ include "incloud-web-resources.sidebar.menu.items.namespaced" . | nindent 4 }}
  {{ else }}
    {{ include "incloud-web-resources.sidebar.menu.items.instance" . | nindent 4 }}
  {{ end }}
