{{- if .Values.addons.argocd.enabled  }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-cluster-argoproj.io.v1alpha1.appprojects"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "AppProject"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "argocd-appproject-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Namespace"
      "title" "Namespace"
      "type" "namespace"
      "jsonPath" ".metadata.namespace"
      "factory" "namespace-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths: []
  additionalPrinterColumnsUndefinedValues: []
  id: "stock-cluster-/argoproj.io/v1alpha1/appprojects"

  {{ if .Values.namespaceNavigation }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-namespace-argoproj.io.v1alpha1.appprojects"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "AppProject"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "argocd-appproject-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths: []
  additionalPrinterColumnsUndefinedValues: []
  id: "stock-namespace-/argoproj.io/v1alpha1/appprojects"
  {{ else }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-project-argoproj.io.v1alpha1.appprojects"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "AppProject"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "argocd-appproject-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths: []
  additionalPrinterColumnsUndefinedValues: []
  id: "stock-project-/argoproj.io/v1alpha1/appprojects"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-instance-argoproj.io.v1alpha1.appprojects"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "title" "AppProject"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "argocd-appproject-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths: []
  additionalPrinterColumnsUndefinedValues: []
  id: "stock-instance-/argoproj.io/v1alpha1/appprojects"
  {{ end }}
{{- end -}}
