---
apiVersion: front.in-cloud.io/v1alpha1
kind: Sidebar
metadata:
  name: stock-project-factory-daemonset-details
spec:
  id: stock-project-factory-daemonset-details
  keysAndTags:
    daemonsets:
      - daemonset-details
  menuItems:
    {{ include "incloud-web-resources.sidebar.menu.items.namespaced" . | nindent 4 }}
