{{- if .Values.addons.trivy.enabled }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "factory-aquasecurity.github.io.v1alpha1.vulnerabilityreports"
spec:
  additionalPrinterColumns:
    - jsonPath: .severity
      name: Severity
      type: string
    - jsonPath: .vulnerabilityID
      name: Vulnerability ID
      type: string
    - jsonPath: .installedVersion
      name: Installed version
      type: string
    - jsonPath: .fixedVersion
      name: Fixed version
      type: string
    - jsonPath: .score
      name: Score
      type: string
    - jsonPath: .resource
      name: Resource
      type: string
  additionalPrinterColumnsUndefinedValues:
    - key: Severity
      value: "-"
    - key: Vulnerability ID
      value: "-"
    - key: Installed version
      value: "-"
    - key: Fixed version
      value: "-"
    - key: Score
      value: "-"
    - key: Resource
      value: "-"
  id: "factory-aquasecurity.github.io.v1alpha1.vulnerabilityreports"


---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "factory-aquasecurity.github.io.v1alpha1.sbomreports"
spec:
  additionalPrinterColumns:
    - jsonPath: .name
      name: Name
      type: string
    - jsonPath: .version
      name: Version
      type: string
    - jsonPath: .type
      name: Type
      type: string
    - jsonPath: .licenses[?(@.license)].license.name
      name: License
      type: array

  additionalPrinterColumnsTrimLengths:
    - key: title
      value: 128
  additionalPrinterColumnsUndefinedValues:
    - key: License
      value: "-"
  id: "factory-aquasecurity.github.io.v1alpha1.sbomreports"
{{- end -}}
