{{ $projRes := .Values.projectResource }}
{{ $instRes := .Values.instanceResource }}

---
apiVersion: front.in-cloud.io/v1alpha1
kind: Navigation
metadata:
  name: navigation
spec:
{{ if .Values.namespaceNavigation }}
  projects:
    clear: "/openapi-ui/{selectedCluster}/builtin-table/pods"
    change: "/openapi-ui/{selectedCluster}/{value}/builtin-table/pods"
  instances:
    clear: "/openapi-ui/{selectedCluster}/builtin-table/pods"
    change: "/openapi-ui/{selectedCluster}/{value}/builtin-table/pods"
  namespaces:
    clear: "/openapi-ui/{selectedCluster}/builtin-table/pods"
    change: "/openapi-ui/{selectedCluster}/{value}/builtin-table/pods"
{{ else }}
  projects:
    clear: "/openapi-ui/clusters/{selectedCluster}"
    # change: "/openapi-ui/{selectedCluster}/{value}/api-table/{{ $instRes.apiGroup }}/{{ $instRes.apiVersion }}/{{ $instRes.resourceName }}"
    change: "/openapi-ui/{selectedCluster}/factory/project-details/{value}"
  instances:
    clear: "/openapi-ui/{selectedCluster}/{selectedProject}/api-table/{{ $instRes.apiGroup }}/{{ $instRes.apiVersion }}/{{ $instRes.resourceName }}"
    change: "/openapi-ui/{selectedCluster}/{value}/{selectedProject}/api-table/apps/v1/deployments"
  namespaces:
    clear: "/openapi-ui/clusters/{selectedCluster}"
    change: "/openapi-ui/clusters/{selectedCluster}/{{ $projRes.resourceName }}/{value}"
{{ end }}
