{{ $projRes := .Values.projectResource }}
{{ $instRes := .Values.instanceResource }}

---
apiVersion: front.in-cloud.io/v1alpha1
kind: Navigation
metadata:
  name: navigation
spec:
{{ if .Values.namespaceNavigation }}
  projects:
    clear: "/{{ .Values.basePrefix }}/{selectedCluster}/builtin-table/pods"
    change: "/{{ .Values.basePrefix }}/{selectedCluster}/{value}/builtin-table/pods"
  instances:
    clear: "/{{ .Values.basePrefix }}/{selectedCluster}/builtin-table/pods"
    change: "/{{ .Values.basePrefix }}/{selectedCluster}/{value}/builtin-table/pods"
  namespaces:
    clear: "/{{ .Values.basePrefix }}/{selectedCluster}/builtin-table/pods"
    change: "/{{ .Values.basePrefix }}/{selectedCluster}/{value}/builtin-table/pods"
{{ else }}
  projects:
    clear: "/{{ .Values.basePrefix }}/clusters/{selectedCluster}"
  {{ if $projRes.deployDefaultForms }}
    change: "/{{ .Values.basePrefix }}/{selectedCluster}/{value}/factory/project-details/{value}"
  {{ else }}
    change: "/{{ .Values.basePrefix }}/{selectedCluster}/{value}/api-table/{{ $instRes.apiGroup }}/{{ $instRes.apiVersion }}/{{ $instRes.resourceName }}"
  {{ end }}
  instances:
    clear: "/{{ .Values.basePrefix }}/{selectedCluster}/{selectedProject}/api-table/{{ $instRes.apiGroup }}/{{ $instRes.apiVersion }}/{{ $instRes.resourceName }}"
    change: "/{{ .Values.basePrefix }}/{selectedCluster}/{value}/{selectedProject}/api-table/apps/v1/deployments"
    mapOptionsPattern: "{{ .Values.instanceResource.instanceNamespaceNavigationPattern }}"
  namespaces:
    clear: "/{{ .Values.basePrefix }}/clusters/{selectedCluster}"
    change: "/{{ .Values.basePrefix }}/clusters/{selectedCluster}/{{ $projRes.resourceName }}/{value}"
{{ end }}

  baseFactoriesMapping:
    base-factory-clusterscoped-api-apiextensions.k8s.io-v1-customresourcedefinitions: crd-details
    base-factory-namespaced-api-apiextensions.k8s.io-v1-customresourcedefinitions: crd-details

    base-factory-clusterscoped-api-apps-v1-daemonsets: daemonset-details
    base-factory-namespaced-api-apps-v1-daemonsets: daemonset-details
    base-factory-clusterscoped-api-apps-v1-instance-daemonsets: instance-daemonset-details
    base-factory-namespaced-api-apps-v1-instance-daemonsets: instance-daemonset-details

    base-factory-clusterscoped-api-apps-v1-deployments: deployment-details
    base-factory-namespaced-api-apps-v1-deployments: deployment-details
    base-factory-clusterscoped-api-apps-v1-instance-deployments: instance-deployment-details
    base-factory-namespaced-api-apps-v1-instance-deployments: instance-deployment-details

    base-factory-clusterscoped-api-apps-v1-replicasets: replicaset-details
    base-factory-namespaced-api-apps-v1-replicasets: replicaset-details
    base-factory-clusterscoped-api-apps-v1-instance-replicasets: instance-replicaset-details
    base-factory-namespaced-api-apps-v1-instance-replicasets: instance-replicaset-details

    base-factory-clusterscoped-api-apps-v1-statefulsets: statefulset-details
    base-factory-namespaced-api-apps-v1-statefulsets: statefulset-details
    base-factory-clusterscoped-api-apps-v1-instance-statefulsets: instance-statefulset-details
    base-factory-namespaced-api-apps-v1-instance-statefulsets: instance-statefulset-details

    base-factory-clusterscoped-api-autoscaling-v2-horizontalpodautoscalers: horizontalpodautoscaler-details
    base-factory-namespaced-api-autoscaling-v2-horizontalpodautoscalers: horizontalpodautoscaler-details
    base-factory-clusterscoped-api-autoscaling-v2-instance-horizontalpodautoscalers: instance-horizontalpodautoscaler-details
    base-factory-namespaced-api-autoscaling-v2-instance-horizontalpodautoscalers: instance-horizontalpodautoscaler-details

    base-factory-clusterscoped-api-batch-v1-cronjobs: cronjob-details
    base-factory-namespaced-api-batch-v1-cronjobs: cronjob-details
    base-factory-clusterscoped-api-batch-v1-instance-cronjobs: instance-cronjob-details
    base-factory-namespaced-api-batch-v1-instance-cronjobs: instance-cronjob-details

    base-factory-clusterscoped-api-batch-v1-jobs: job-details
    base-factory-namespaced-api-batch-v1-jobs: job-details
    base-factory-clusterscoped-api-batch-v1-instance-jobs: instance-job-details
    base-factory-namespaced-api-batch-v1-instance-jobs: instance-job-details

    base-factory-clusterscoped-api-cert-manager.io-v1-certificates: certificate-details
    base-factory-namespaced-api-cert-manager.io-v1-certificates: certificate-details

    base-factory-clusterscoped-builtin-v1-secrets: secret-details
    base-factory-namespaced-builtin-v1-secrets: secret-details
    base-factory-clusterscoped-builtin-v1-instance-secrets: instance-secret-details
    base-factory-namespaced-builtin-v1-instance-secrets: instance-secret-details

    base-factory-clusterscoped-builtin-v1-pods: pod-details
    base-factory-namespaced-builtin-v1-pods: pod-details
    base-factory-clusterscoped-builtin-v1-instance-pods: instance-pod-details
    base-factory-namespaced-builtin-v1-instance-pods: instance-pod-details

    base-factory-clusterscoped-api-networking.k8s.io-v1-networkpolicies: networkpolicy-details
    base-factory-namespaced-api-networking.k8s.io-v1-networkpolicies: networkpolicy-details
    base-factory-clusterscoped-api-networking.k8s.io-v1-instance-networkpolicies: instance-networkpolicy-details
    base-factory-namespaced-api-networking.k8s.io-v1-instance-networkpolicies: instance-networkpolicy-details

    base-factory-clusterscoped-api-policy-v1-poddisruptionbudgets: poddisruptionbudget-details
    base-factory-namespaced-api-policy-v1-poddisruptionbudgets: poddisruptionbudget-details
    base-factory-clusterscoped-api-policy-v1-instance-poddisruptionbudgets: instance-poddisruptionbudget-details
    base-factory-namespaced-api-policy-v1-instance-poddisruptionbudgets: instance-poddisruptionbudget-details

    base-factory-clusterscoped-api-rbac.authorization.k8s.io-v1-clusterrolebindings: clusterrolebinding-details
    base-factory-namespaced-api-rbac.authorization.k8s.io-v1-clusterrolebindings: clusterrolebinding-details

    base-factory-clusterscoped-api-rbac.authorization.k8s.io-v1-clusterroles: clusterrole-details
    base-factory-namespaced-api-rbac.authorization.k8s.io-v1-clusterroles: clusterrole-details

    base-factory-clusterscoped-api-rbac.authorization.k8s.io-v1-rolebindings: rolebinding-details
    base-factory-namespaced-api-rbac.authorization.k8s.io-v1-rolebindings: rolebinding-details

    base-factory-clusterscoped-api-rbac.authorization.k8s.io-v1-roles: role-details
    base-factory-namespaced-api-rbac.authorization.k8s.io-v1-roles: role-details

    base-factory-clusterscoped-builtin-v1-configmaps: configmap-details
    base-factory-namespaced-builtin-v1-configmaps: configmap-details
    base-factory-clusterscoped-builtin-v1-instance-configmaps: instance-configmap-details
    base-factory-namespaced-builtin-v1-instance-configmaps: instance-configmap-details

    base-factory-clusterscoped-builtin-v1-nodes: node-details

    base-factory-clusterscoped-builtin-v1-replicationcontrollers: replicationcontroller-details
    base-factory-namespaced-builtin-v1-replicationcontrollers: replicationcontroller-details
    base-factory-clusterscoped-builtin-v1-instance-replicationcontrollers: instance-replicationcontroller-details
    base-factory-namespaced-builtin-v1-instance-replicationcontrollers: instance-replicationcontroller-details

    base-factory-clusterscoped-builtin-v1-serviceaccounts: serviceaccount-details
    base-factory-namespaced-builtin-v1-serviceaccounts: serviceaccount-details
    base-factory-clusterscoped-builtin-v1-instance-serviceaccounts: instance-serviceaccount-details
    base-factory-namespaced-builtin-v1-instance-serviceaccounts: instance-serviceaccount-details

    base-factory-clusterscoped-builtin-v1-services: service-details
    base-factory-namespaced-builtin-v1-services: service-details
    base-factory-clusterscoped-builtin-v1-instance-services: instance-service-details
    base-factory-namespaced-builtin-v1-instance-services: instance-service-details

    base-factory-namespaced-api-argoproj.io-v1alpha1-applications: argocd-application-details
    base-factory-namespaced-api-argoproj.io-v1alpha1-appprojects: argocd-appproject-details
