---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomFormsOverride
metadata:
  name: default-v1.secrets
spec:
  customizationId: "default-/v1/secrets"
  hidden:
    {{ include "incloud-web-resources.customformoverride.hidden.metadata.system" . | nindent 4 }}
    {{ include "incloud-web-resources.customformoverride.hidden.metadata.api" . | nindent 4 }}
    {{ include "incloud-web-resources.customformoverride.hidden.status" . | nindent 4 }}
    - - immutable
    - - stringData
  sort:
    - - data
    - - metadata
      - name
    - - metadata
      - namespace
    - - metadata
      - annotations
    - - metadata
      - labels
  schema:
    properties:
      data:
        description: >
          Data contains the configuration data. Each key must consist of alphanumeric
          characters, '-', '_' or '.'. Values with non-UTF-8 byte sequences must use
          the BinaryData field. The keys stored in Data must not overlap with the keys
          in the BinaryData field, this is enforced during validation process.
        type: object
        additionalProperties:
          type: multilineStringBase64
  strategy: merge

