---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-project-factory-cronjob-details
spec:
  id: "stock-project-factory-cronjob-details"
  breadcrumbItems:
    - key: cronjob
      label: "batch/v1/cronjobs"
      link: "/openapi-ui/{clusterName}/{namespace}/api-table/batch/v1/cronjobs"
    - key: cronjob
      label: "{6}"

{{- if not .Values.namespaceNavigation }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-instance-factory-instance-cronjob-details
spec:
  id: "stock-instance-factory-instance-cronjob-details"
  breadcrumbItems:
    - key: cronjob
      label: "batch/v1/cronjobs"
      link: "/openapi-ui/{clusterName}/{namespace}/{syntheticProject}/api-table/batch/v1/cronjobs"
    - key: cronjob
      label: "{7}"
{{- end }}
