---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-project-factory-pod-details
spec:
  id: "stock-project-factory-pod-details"
  breadcrumbItems:
    - key: pods
      label: "v1/pods"
      link: "/{{ .Values.basePrefix }}/{cluster}/{namespace}/builtin-table/pods"
    - key: pod
      label: "{8}"

{{- if not .Values.namespaceNavigation }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-instance-factory-instance-pod-details
spec:
  id: "stock-instance-factory-instance-pod-details"
  breadcrumbItems:
    - key: pods
      label: "v1/pods"
      link: "/{{ .Values.basePrefix }}/{cluster}/{namespace}/{syntheticProject}/builtin-table/pods"
    - key: pod
      label: "{9}"
{{- end -}}
