---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-project-factory-secret-details
spec:
  id: "stock-project-factory-secret-details"
  breadcrumbItems:
    - key: secrets
      label: "v1/secrets"
      link: "/{{ .Values.basePrefix }}/{cluster}/{namespace}/builtin-table/secrets"
    - key: secret
      label: "{8}"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-instance-factory-instance-secret-details
spec:
  id: "stock-instance-factory-instance-secret-details"
  breadcrumbItems:
    - key: secrets
      label: "v1/secrets"
      link: "/{{ .Values.basePrefix }}/{cluster}/{namespace}/{syntheticProject}/builtin-table/secrets"
    - key: secret
      label: "{9}"
