---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-project-factory-statefulset-details
spec:
  id: "stock-project-factory-statefulset-details"
  breadcrumbItems:
    - key: statefulsets
      label: "apps/v1/statefulsets"
      link: "/{{ .Values.basePrefix }}/{cluster}/{namespace}/api-table/apps/v1/statefulsets"
    - key: statefulset
      label: "{9}"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-instance-factory-instance-statefulset-details
spec:
  id: "stock-instance-factory-instance-statefulset-details"
  breadcrumbItems:
    - key: statefulsets
      label: "apps/v1/statefulsets"
      link: "/{{ .Values.basePrefix }}/{cluster}/{namespace}/{syntheticProject}/api-table/apps/v1/statefulsets"
    - key: statefulset
      label: "{10}"
